# Generated by Django 3.2.16 on 2022-12-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tongsinsa_backend', '0002_auto_20221227_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
