# Generated by Django 3.2.16 on 2022-12-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tongsinsa_backend', '0003_auto_20221227_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
    ]
