# Generated by Django 3.2.16 on 2022-12-29 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tongsinsa_backend', '0004_auto_20221227_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_generated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('writer', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('info', models.JSONField()),
                ('info_image', models.URLField(default='default_info_image.png')),
                ('thumbnail', models.URLField(default='default_thumbnail_image.png')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_image',
            field=models.URLField(default='default_user_image.png'),
        ),
    ]
